// Date: 10.06.2014 10:20:18
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSaltBath extends ModelBase
{
  //fields
    ModelRenderer Shape2;
    ModelRenderer Shape1;
    ModelRenderer Shape4;
    ModelRenderer Shape3;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
  
  public ModelSaltBath()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 14, 3, 1);
      Shape2.setRotationPoint(-7F, 21F, -7F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 14, 3, 1);
      Shape1.setRotationPoint(-7F, 21F, 6F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 3, 12);
      Shape4.setRotationPoint(-7F, 21F, -6F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 3, 12);
      Shape3.setRotationPoint(6F, 21F, -6F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 12, 0, 12);
      Shape5.setRotationPoint(-6F, 23.9F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 51, 0);
      Shape6.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape6.setRotationPoint(-6F, 23F, -6F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 18);
      Shape7.addBox(0F, 0F, 0F, 2, 1, 4);
      Shape7.setRotationPoint(-6F, 23.2F, -5F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 37, 0);
      Shape8.addBox(0F, 0F, 0F, 4, 1, 3);
      Shape8.setRotationPoint(-6F, 23.3F, 0F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 24);
      Shape9.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape9.setRotationPoint(-6F, 23F, -1F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 6);
      Shape10.addBox(0F, 0F, 0F, 4, 1, 2);
      Shape10.setRotationPoint(-3F, 23.5F, -6F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 27);
      Shape11.addBox(0F, 0F, 0F, 3, 1, 4);
      Shape11.setRotationPoint(-4F, 23F, -5F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 14, 19);
      Shape12.addBox(0F, 0F, 0F, 4, 1, 2);
      Shape12.setRotationPoint(-3F, 23.4F, -1F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 26, 16);
      Shape13.addBox(0F, 0F, 0F, 5, 1, 4);
      Shape13.setRotationPoint(-6F, 23F, 2F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 15, 16);
      Shape14.addBox(0F, 0F, 0F, 2, 1, 3);
      Shape14.setRotationPoint(-1F, 23.2F, -4F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 12, 24);
      Shape15.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape15.setRotationPoint(-1F, 23.2F, 4F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 24, 22);
      Shape16.addBox(0F, 0F, 0F, 3, 1, 3);
      Shape16.setRotationPoint(-2F, 23.3F, 1F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 53, 5);
      Shape17.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape17.setRotationPoint(0F, 23.2F, -6F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 38, 6);
      Shape18.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape18.setRotationPoint(0F, 23F, -4F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 52, 10);
      Shape19.addBox(0F, 0F, 0F, 4, 1, 2);
      Shape19.setRotationPoint(0F, 23F, 0F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 55, 16);
      Shape20.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape20.setRotationPoint(3F, 23.1F, 0F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 48, 20);
      Shape21.addBox(0F, 0F, 0F, 4, 1, 3);
      Shape21.setRotationPoint(2F, 23.3F, 3F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 20, 28);
      Shape22.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape22.setRotationPoint(3F, 23.2F, 1F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 44, 14);
      Shape23.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape23.setRotationPoint(1F, 23.4F, 2F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 50, 27);
      Shape24.addBox(0F, 0F, 0F, 2, 1, 3);
      Shape24.setRotationPoint(4F, 23F, -3F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 27, 13);
      Shape25.addBox(0F, 0F, 0F, 2, 1, 3);
      Shape25.setRotationPoint(3F, 23.2F, -5F);
      Shape25.setTextureSize(64, 32);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 1, 16);
      Shape26.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape26.setRotationPoint(3F, 23.4F, -6F);
      Shape26.setTextureSize(64, 32);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 38, 26);
      Shape27.addBox(0F, 0F, 0F, 1, 1, 3);
      Shape27.setRotationPoint(5F, 23F, -6F);
      Shape27.setTextureSize(64, 32);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 45, 11);
      Shape28.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape28.setRotationPoint(1F, 23.2F, -2F);
      Shape28.setTextureSize(64, 32);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 14, 28);
      Shape29.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape29.setRotationPoint(2F, 23.1F, -4F);
      Shape29.setTextureSize(64, 32);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape2.render(f5);
    Shape1.render(f5);
    Shape4.render(f5);
    Shape3.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
public void renderAll()
{
	float f5 = 0.0625F;
    Shape2.render(f5);
    Shape1.render(f5);
    Shape4.render(f5);
    Shape3.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
}

}
