// Date: 20.01.2013 23:08:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
@SideOnly(Side.CLIENT)
public class ModelMammoth extends ModelBase
{
  //fields
    ModelRenderer FatLayer;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Head;
    ModelRenderer Slurf1;
    ModelRenderer Slurf2;
    ModelRenderer Slurf3;
    ModelRenderer Slurf4;
    ModelRenderer Slurf5;
    ModelRenderer Body;
    ModelRenderer LSlagtand1;
    ModelRenderer LSlagtand2;
    ModelRenderer LSlagtand3;
    ModelRenderer RSlagtand1;
    ModelRenderer RSlagtand2;
    ModelRenderer RSlagtand3;
    ModelRenderer Tail;
    ModelRenderer EarL;
    ModelRenderer EarR;
    ModelRenderer Bult;
    ModelRenderer BultTops;
  
  public ModelMammoth()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      FatLayer = new ModelRenderer(this, 373, 0);
      FatLayer.addBox(0F, 0F, 0F, 32, 27, 33);
      FatLayer.setRotationPoint(-15F, -23F, 4F);
      FatLayer.setTextureSize(64, 32);
      FatLayer.mirror = true;
      setRotation(FatLayer, -0.0371755F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 300, 63);
      Leg1.addBox(0F, 0F, 0F, 8, 24, 8);
      Leg1.setRotationPoint(10F, 0F, 0F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 300, 100);
      Leg2.addBox(0F, 0F, 0F, 8, 24, 8);
      Leg2.setRotationPoint(-16F, 0F, 0F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 250, 100);
      Leg3.addBox(0F, 0F, 0F, 8, 21, 8);
      Leg3.setRotationPoint(10F, 3F, 32F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 250, 62);
      Leg4.addBox(0F, 0F, 0F, 8, 21, 8);
      Leg4.setRotationPoint(-16F, 3F, 32F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 300, 0);
      Head.addBox(0F, 0F, 0F, 18, 15, 12);
      Head.setRotationPoint(-8F, -23F, -12F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Slurf1 = new ModelRenderer(this, 50, 0);
      Slurf1.addBox(-3F, 0F, 0F, 6, 12, 4);
      Slurf1.setRotationPoint(1F, -12F, -11F);
      Slurf1.setTextureSize(64, 32);
      Slurf1.mirror = true;
      setRotation(Slurf1, -0.7063936F, 0F, 0F);
      Slurf2 = new ModelRenderer(this, 50, 20);
      Slurf2.addBox(-3F, 11F, -3F, 6, 10, 4);
      Slurf2.setRotationPoint(1F, -12F, -11F);
      Slurf2.setTextureSize(64, 32);
      Slurf2.mirror = true;
      setRotation(Slurf2, -0.4089647F, 0F, 0F);
      Slurf3 = new ModelRenderer(this, 50, 39);
      Slurf3.addBox(-2F, 20F, -5F, 4, 5, 2);
      Slurf3.setRotationPoint(1F, -12F, -11F);
      Slurf3.setTextureSize(64, 32);
      Slurf3.mirror = true;
      setRotation(Slurf3, -0.2602503F, 0F, 0F);
      Slurf4 = new ModelRenderer(this, 66, 40);
      Slurf4.addBox(-2F, 18F, -18F, 4, 5, 2);
      Slurf4.setRotationPoint(1F, -12F, -11F);
      Slurf4.setTextureSize(64, 32);
      Slurf4.mirror = true;
      setRotation(Slurf4, 0.3346075F, 0F, 0F);
      Slurf5 = new ModelRenderer(this, 83, 40);
      Slurf5.addBox(-2F, -3F, -29F, 4, 3, 2);
      Slurf5.setRotationPoint(1F, -12F, -11F);
      Slurf5.setTextureSize(64, 32);
      Slurf5.mirror = true;
      setRotation(Slurf5, 1.33843F, 0F, 0F);
      Body = new ModelRenderer(this, 373, 85);
      Body.addBox(0F, 0F, 0F, 28, 23, 40);
      Body.setRotationPoint(-13F, -21F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, -0.0371755F, 0F, 0F);
      LSlagtand1 = new ModelRenderer(this, 0, 87);
      LSlagtand1.addBox(0F, 0F, -12F, 2, 2, 12);
      LSlagtand1.setRotationPoint(7F, -8F, -9F);
      LSlagtand1.setTextureSize(64, 32);
      LSlagtand1.mirror = true;
      setRotation(LSlagtand1, 2.621101F, 2.695451F, 0F);
      LSlagtand2 = new ModelRenderer(this, 0, 69);
      LSlagtand2.addBox(0F, 0F, -12F, 2, 2, 12);
      LSlagtand2.setRotationPoint(10F, -4F, -19F);
      LSlagtand2.setTextureSize(64, 32);
      LSlagtand2.mirror = true;
      setRotation(LSlagtand2, 0.7435722F, 0.6252203F, 0.0371786F);
      LSlagtand3 = new ModelRenderer(this, 0, 56);
      LSlagtand3.addBox(0F, 0F, -7F, 2, 2, 6);
      LSlagtand3.setRotationPoint(7F, 4F, -24F);
      LSlagtand3.setTextureSize(64, 32);
      LSlagtand3.mirror = true;
      setRotation(LSlagtand3, -0.0743572F, 1.152537F, 0.0371786F);
      RSlagtand1 = new ModelRenderer(this, 0, 35);
      RSlagtand1.addBox(0F, 0F, -12F, 2, 2, 12);
      RSlagtand1.setRotationPoint(-6F, -10F, -11F);
      RSlagtand1.setTextureSize(64, 32);
      RSlagtand1.mirror = true;
      setRotation(RSlagtand1, 0.5205006F, 0.4461433F, 0F);
      RSlagtand2 = new ModelRenderer(this, 0, 15);
      RSlagtand2.addBox(0F, 0F, -12F, 2, 2, 12);
      RSlagtand2.setRotationPoint(-10F, -5F, -20F);
      RSlagtand2.setTextureSize(64, 32);
      RSlagtand2.mirror = true;
      setRotation(RSlagtand2, 0.7063936F, -0.4089647F, 0.2230717F);
      RSlagtand3 = new ModelRenderer(this, 0, 0);
      RSlagtand3.addBox(0F, 0F, -7F, 2, 2, 6);
      RSlagtand3.setRotationPoint(-9F, 2F, -28F);
      RSlagtand3.setTextureSize(64, 32);
      RSlagtand3.mirror = true;
      setRotation(RSlagtand3, -0.0743572F, -1.115358F, 0.0371786F);
      Tail = new ModelRenderer(this, 131, 0);
      Tail.addBox(0F, 0F, 0F, 4, 2, 14);
      Tail.setRotationPoint(-1F, -16F, 40F);
      Tail.setTextureSize(64, 32);
      Tail.mirror = true;
      setRotation(Tail, -1.152537F, 0F, 0F);
      EarL = new ModelRenderer(this, 200, 14);
      EarL.addBox(-11F, 0F, 0F, 11, 9, 0);
      EarL.setRotationPoint(9F, -22F, -10F);
      EarL.setTextureSize(64, 32);
      EarL.mirror = true;
      setRotation(EarL, 0.1487144F, 2.621092F, 0F);
      EarR = new ModelRenderer(this, 200, 0);
      EarR.addBox(-11F, 0F, 0F, 11, 9, 0);
      EarR.setRotationPoint(-7F, -22F, -9F);
      EarR.setTextureSize(64, 32);
      EarR.mirror = true;
      setRotation(EarR, -0.0371786F, 0.5576792F, 0F);
      Bult = new ModelRenderer(this, 300, 36);
      Bult.addBox(0F, 0F, 0F, 10, 3, 6);
      Bult.setRotationPoint(-4F, -26F, -9F);
      Bult.setTextureSize(64, 32);
      Bult.mirror = true;
      setRotation(Bult, 0F, 0F, 0F);
      BultTops = new ModelRenderer(this, 300, 50);
      BultTops.addBox(0F, 0F, 0F, 12, 1, 8);
      BultTops.setRotationPoint(-5F, -27F, -10F);
      BultTops.setTextureSize(64, 32);
      BultTops.mirror = true;
      setRotation(BultTops, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    if (this.isChild)
    {
        float var8 = 2.0F;
        GL11.glPushMatrix();
        GL11.glTranslatef(0.0F, 5.0F * f5, 2.0F * f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
        GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
        FatLayer.render(f5);
        Leg1.render(f5);
        Leg2.render(f5);
        Leg3.render(f5);
        Leg4.render(f5);
        Head.render(f5);
        Slurf1.render(f5);
        Slurf2.render(f5);
        Slurf3.render(f5);
        Slurf4.render(f5);
        Slurf5.render(f5);
        Body.render(f5);
        LSlagtand1.render(f5);
        LSlagtand2.render(f5);
        LSlagtand3.render(f5);
        RSlagtand1.render(f5);
        RSlagtand2.render(f5);
        RSlagtand3.render(f5);
        Tail.render(f5);
        EarL.render(f5);
        EarR.render(f5);
        Bult.render(f5);
        BultTops.render(f5);
        GL11.glPopMatrix();
        
    }
    else
    {
    FatLayer.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Head.render(f5);
    Slurf1.render(f5);
    Slurf2.render(f5);
    Slurf3.render(f5);
    Slurf4.render(f5);
    Slurf5.render(f5);
    Body.render(f5);
    LSlagtand1.render(f5);
    LSlagtand2.render(f5);
    LSlagtand3.render(f5);
    RSlagtand1.render(f5);
    RSlagtand2.render(f5);
    RSlagtand3.render(f5);
    Tail.render(f5);
    EarL.render(f5);
    EarR.render(f5);
    Bult.render(f5);
    BultTops.render(f5);
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg3.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    Leg4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
