// Date: 04.09.2014 17:54:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBison extends ModelBase
{
  //fields
    ModelRenderer foot1;
    ModelRenderer foot2;
    ModelRenderer thingy3;
    ModelRenderer thingy1;
    ModelRenderer bodypart;
    ModelRenderer bodymain;
    ModelRenderer thingy4;
    ModelRenderer foot5;
    ModelRenderer thingy2;
    ModelRenderer foot4;
    ModelRenderer head;
    ModelRenderer headtop;
    ModelRenderer horn1;
    ModelRenderer horn3;
    ModelRenderer horn4;
    ModelRenderer horn2;
  
  public ModelBison()
  {
    textureWidth = 256;
    textureHeight = 128;
    
    
    foot1 = new ModelRenderer(this, 130, 0);
    foot1.addBox(0F, 3F, 0F, 3, 5, 3);
    foot1.setRotationPoint(-8F, 16F, 0F);
    foot1.setTextureSize(256, 128);
    foot1.mirror = true;
    setRotation(foot1, 0F, 0F, 0F);
    foot2 = new ModelRenderer(this, 130, 0);
    foot2.addBox(1F, 3F, 2F, 3, 5, 3);
    foot2.setRotationPoint(4F, 16F, -1F);
    foot2.setTextureSize(256, 128);
    foot2.mirror = true;
    setRotation(foot2, 0F, 0F, 0F);
    thingy3 = new ModelRenderer(this, 110, 0);
    thingy3.addBox(0F, -3F, 0F, 4, 6, 5);
    thingy3.setRotationPoint(-8.5F, 16F, -0.5F);
    thingy3.setTextureSize(256, 128);
    thingy3.mirror = true;
    setRotation(thingy3, 0F, 0F, 0F);
    thingy1 = new ModelRenderer(this, 110, 0);
    thingy1.addBox(0F, -3F, 0F, 4, 6, 5);
    thingy1.setRotationPoint(4.5F, 16F, -0.5F);
    thingy1.setTextureSize(256, 128);
    thingy1.mirror = true;
    setRotation(thingy1, 0F, 0F, 0F);
    bodypart = new ModelRenderer(this, 0, 40);
    bodypart.addBox(0F, 0F, 0F, 15, 14, 16);
    bodypart.setRotationPoint(-7.5F, 2F, -10F);
    bodypart.setTextureSize(256, 128);
    bodypart.mirror = true;
    setRotation(bodypart, 0F, 0F, 0F);
    bodymain = new ModelRenderer(this, 0, 0);
    bodymain.addBox(0F, -1F, 0F, 18, 16, 18);
    bodymain.setRotationPoint(-9F, 2F, -23F);
    bodymain.setTextureSize(256, 128);
    bodymain.mirror = true;
    setRotation(bodymain, 0F, 0F, 0F);
    thingy4 = new ModelRenderer(this, 145, 0);
    thingy4.addBox(0F, -4F, 0F, 4, 6, 5);
    thingy4.setRotationPoint(4.5F, 17F, -21F);
    thingy4.setTextureSize(256, 128);
    thingy4.mirror = true;
    setRotation(thingy4, 0F, 0F, 0F);
    foot5 = new ModelRenderer(this, 165, 0);
    foot5.addBox(1F, 2F, 1F, 3, 5, 3);
    foot5.setRotationPoint(4F, 17F, -21F);
    foot5.setTextureSize(256, 128);
    foot5.mirror = true;
    setRotation(foot5, 0F, 0F, 0F);
    thingy2 = new ModelRenderer(this, 145, 0);
    thingy2.addBox(0F, -4F, 0F, 4, 6, 5);
    thingy2.setRotationPoint(-8.5F, 17F, -21F);
    thingy2.setTextureSize(256, 128);
    thingy2.mirror = true;
    setRotation(thingy2, 0F, 0F, 0F);
    foot4 = new ModelRenderer(this, 165, 0);
    foot4.addBox(0F, 2F, 1F, 3, 5, 3);
    foot4.setRotationPoint(-8F, 17F, -21F);
    foot4.setTextureSize(256, 128);
    foot4.mirror = true;
    setRotation(foot4, 0F, 0F, 0F);
    head = new ModelRenderer(this, 0, 75);
    head.addBox(0F, 0F, 0F, 8, 8, 8);
    head.setRotationPoint(-4F, 7F, -31F);
    head.setTextureSize(256, 128);
    head.mirror = true;
    setRotation(head, 0F, 0F, 0F);
    headtop = new ModelRenderer(this, 0, 95);
    headtop.addBox(0F, 0F, 0F, 10, 5, 9);
    headtop.setRotationPoint(-5F, 3F, -32F);
    headtop.setTextureSize(256, 128);
    headtop.mirror = true;
    setRotation(headtop, 0F, 0F, 0F);
    horn1 = new ModelRenderer(this, 90, 0);
    horn1.addBox(0F, 0F, 0F, 2, 2, 2);
    horn1.setRotationPoint(-7F, 4F, -28F);
    horn1.setTextureSize(256, 128);
    horn1.mirror = true;
    setRotation(horn1, 0F, 0F, 0F);
    horn3 = new ModelRenderer(this, 90, 0);
    horn3.addBox(0F, 0F, 0F, 2, 2, 2);
    horn3.setRotationPoint(5F, 4F, -28F);
    horn3.setTextureSize(256, 128);
    horn3.mirror = true;
    setRotation(horn3, 0F, 0F, 0F);
    horn4 = new ModelRenderer(this, 75, 0);
    horn4.addBox(0F, 0F, 0F, 2, 5, 2);
    horn4.setRotationPoint(7F, 1F, -28F);
    horn4.setTextureSize(256, 128);
    horn4.mirror = true;
    setRotation(horn4, 0F, 0F, 0F);
    horn2 = new ModelRenderer(this, 75, 0);
    horn2.addBox(0F, 0F, 0F, 2, 5, 2);
    horn2.setRotationPoint(-9F, 1F, -28F);
    horn2.setTextureSize(256, 128);
    horn2.mirror = true;
    setRotation(horn2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    foot1.render(f5);
    foot2.render(f5);
    thingy3.render(f5);
    thingy1.render(f5);
    bodypart.render(f5);
    bodymain.render(f5);
    thingy4.render(f5);
    foot5.render(f5);
    thingy2.render(f5);
    foot4.render(f5);
    head.render(f5);
    headtop.render(f5);
    horn1.render(f5);
    horn3.render(f5);
    horn4.render(f5);
    horn2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    foot1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    thingy3.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    foot5.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    thingy4.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    foot2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    thingy1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    thingy2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    foot4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
