// Date: 07.06.2014 14:59:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelElephantHelmet extends ModelBiped
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape6;
    ModelRenderer Shape5;
  
  public ModelElephantHelmet(float f)
  {
	  super(f, 0, 64, 64);
    textureWidth = 64;
    textureHeight = 64;
    

    Shape1 = new ModelRenderer(this, 0, 34);
    Shape1.addBox(-4F, -8F, -4F, 8, 8, 8);
    Shape1.setRotationPoint(0F, 0F, 0F);
    Shape1.setTextureSize(64, 32);
    Shape1.mirror = true;
    setRotation(Shape1, 0F, 0F, 0F);
    Shape2 = new ModelRenderer(this, 37, 39);
    Shape2.addBox(2F, -7F, -3F, 7, 6, 0);
    Shape2.setRotationPoint(0F, 0F, 0F);
    Shape2.setTextureSize(64, 32);
    Shape2.mirror = true;
    setRotation(Shape2, 0F, -0.4461433F, 0F);
    Shape3 = new ModelRenderer(this, 37, 32);
    Shape3.addBox(-9F, -7F, -3F, 7, 6, 0);
    Shape3.setRotationPoint(0F, 0F, 0F);
    Shape3.setTextureSize(64, 32);
    Shape3.mirror = true;
    setRotation(Shape3, 0F, 0.4461411F, 0F);
    Shape4 = new ModelRenderer(this, 36, 50);
    Shape4.addBox(-1F, -5F, -11F, 2, 2, 11);
    Shape4.setRotationPoint(0F, 0F, 0F);
    Shape4.setTextureSize(64, 32);
    Shape4.mirror = true;
    setRotation(Shape4, 0.5205006F, 0F, 0F);
    Shape5 = new ModelRenderer(this, 0, 56);
    Shape5.addBox(2F, -4F, -8F, 1, 1, 7);
    Shape5.setRotationPoint(0F, 0F, 0F);
    Shape5.setTextureSize(64, 32);
    Shape5.mirror = true;
    setRotation(Shape5, 0.669215F, 0F, 0F);
    Shape6 = new ModelRenderer(this, 0, 56);
    Shape6.addBox(-3F, -4F, -8F, 1, 1, 7);
    Shape6.setRotationPoint(0F, 0F, 0F);
    Shape6.setTextureSize(64, 32);
    Shape6.mirror = true;
    setRotation(Shape6, 0.669215F, 0F, 0F);
      
      this.bipedHead.addChild(Shape1);
      this.bipedHead.addChild(Shape2);
      this.bipedHead.addChild(Shape3);
      this.bipedHead.addChild(Shape4);
      this.bipedHead.addChild(Shape5);
      this.bipedHead.addChild(Shape6);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
