// Date: 02.04.2013 10:46:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
@SideOnly(Side.CLIENT)
public class ModelSaberTooth extends ModelLOMBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Leg2;
    ModelRenderer Leg2B;
    ModelRenderer Paw3;
    ModelRenderer Leg4;
    ModelRenderer Paw2;
    ModelRenderer Leg3;
    ModelRenderer Head;
    ModelRenderer JawB;
    ModelRenderer JawT;
    ModelRenderer Teeth2;
    ModelRenderer Teeth1;
    ModelRenderer Ear2;
    ModelRenderer Ear1;
    ModelRenderer Tail;
    ModelRenderer Leg1;
    ModelRenderer Leg1B;
    ModelRenderer Paw1;
    ModelRenderer Paw4;
    ModelRenderer body_2;
    ModelRenderer mane;
    ModelRenderer snout;
    ModelRenderer snout_upper;
    ModelRenderer Head_2;
    ModelRenderer thigh;
    ModelRenderer Teeth_3;
    ModelRenderer Teeth_4;
    ModelRenderer thigh_2;
  
  public ModelSaberTooth()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 10, 8, 19);
      Body.setRotationPoint(-5F, 6F, -2F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 100, 0);
      Leg2.addBox(-1F, -5F, -1F, 4, 8, 6);
      Leg2.setRotationPoint(-6F, 12F, 1F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg2B = new ModelRenderer(this, 120, 20);
      Leg2B.addBox(-1F, 0F, 1F, 3, 10, 4);
      Leg2B.setRotationPoint(-5.5F, 13F, 0F);
      Leg2B.setTextureSize(64, 32);
      Leg2B.mirror = true;
      setRotation(Leg2B, -0.4089647F, 0F, 0F);
      Paw3 = new ModelRenderer(this, 22, 59);
      Paw3.addBox(-1F, 11F, 1F, 5, 2, 6);
      Paw3.setRotationPoint(3F, 11F, 10F);
      Paw3.setTextureSize(64, 32);
      Paw3.mirror = true;
      setRotation(Paw3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 35, 35);
      Leg4.addBox(0F, 0F, 0F, 3, 9, 4);
      Leg4.setRotationPoint(-6F, 15F, 10F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0.3490659F, 0F, 0F);
      Paw2 = new ModelRenderer(this, 136, 0);
      Paw2.addBox(-2F, 9F, -5F, 5, 2, 6);
      Paw2.setRotationPoint(-5.5F, 13F, 0F);
      Paw2.setTextureSize(64, 32);
      Paw2.mirror = true;
      setRotation(Paw2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 35, 35);
      Leg3.addBox(-2F, 5F, -4F, 3, 9, 4);
      Leg3.setRotationPoint(5F, 9F, 12F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0.3490659F, 0F, 0F);
      Head = new ModelRenderer(this, 50, 82);
      Head.addBox(-3F, -3F, -4F, 8, 8, 5);
      Head.setRotationPoint(-1F, 8.5F, -4F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      JawB = new ModelRenderer(this, 50, 124);
      JawB.addBox(0F, 0F, -3F, 3, 1, 3);
      JawB.setRotationPoint(-1.5F, 12F, -9F);
      JawB.setTextureSize(64, 32);
      JawB.mirror = true;
      setRotation(JawB, 0F, 0F, 0F);
      JawT = new ModelRenderer(this, 50, 116);
      JawT.addBox(0F, 0F, -4F, 5, 2, 4);
      JawT.setRotationPoint(-2.5F, 9F, -9F);
      JawT.setTextureSize(64, 32);
      JawT.mirror = true;
      setRotation(JawT, 0F, 0F, 0F);
      Teeth2 = new ModelRenderer(this, 0, 120);
      Teeth2.addBox(0F, 0F, 0F, 1, 2, 1);
      Teeth2.setRotationPoint(-2F, 10F, -12.2F);
      Teeth2.setTextureSize(64, 32);
      Teeth2.mirror = true;
      setRotation(Teeth2, 0F, 0F, 0F);
      Teeth1 = new ModelRenderer(this, 0, 120);
      Teeth1.addBox(0F, 0F, 0F, 1, 2, 1);
      Teeth1.setRotationPoint(1F, 10F, -12.3F);
      Teeth1.setTextureSize(64, 32);
      Teeth1.mirror = true;
      setRotation(Teeth1, 0F, 0F, 0F);
      Ear2 = new ModelRenderer(this, 9, 100);
      Ear2.addBox(-3F, -4F, -2F, 2, 3, 1);
      Ear2.setRotationPoint(-0.5F, 6.6F, -5.5F);
      Ear2.setTextureSize(64, 32);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0.6981317F, -0.6981317F);
      Ear1 = new ModelRenderer(this, 9, 108);
      Ear1.addBox(2F, -4F, -2F, 2, 3, 1);
      Ear1.setRotationPoint(0F, 6F, -6F);
      Ear1.setTextureSize(64, 32);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, -0.6981317F, 0.6981317F);
      Tail = new ModelRenderer(this, 79, 0);
      Tail.addBox(0F, 0F, 0F, 2, 6, 2);
      Tail.setRotationPoint(-1F, 9F, 15F);
      Tail.setTextureSize(64, 32);
      Tail.mirror = true;
      setRotation(Tail, 0.7063936F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 100, 0);
      Leg1.addBox(0F, 0F, 0F, 4, 8, 6);
      Leg1.setRotationPoint(3F, 8F, -1F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg1B = new ModelRenderer(this, 120, 20);
      Leg1B.addBox(-1F, 0F, 0F, 3, 10, 4);
      Leg1B.setRotationPoint(4.5F, 13F, 1F);
      Leg1B.setTextureSize(64, 32);
      Leg1B.mirror = true;
      setRotation(Leg1B, -0.4089647F, 0F, 0F);
      Paw1 = new ModelRenderer(this, 136, 0);
      Paw1.addBox(-2F, 9F, -5F, 5, 2, 6);
      Paw1.setRotationPoint(4.5F, 13F, 0F);
      Paw1.setTextureSize(64, 32);
      Paw1.mirror = true;
      setRotation(Paw1, 0F, 0F, 0F);
      Paw4 = new ModelRenderer(this, 22, 59);
      Paw4.addBox(-1F, 11F, 1F, 5, 2, 6);
      Paw4.setRotationPoint(-6F, 11F, 10F);
      Paw4.setTextureSize(64, 32);
      Paw4.mirror = true;
      setRotation(Paw4, 0F, 0F, 0F);
      body_2 = new ModelRenderer(this, 60, 25);
      body_2.addBox(0F, 0F, 0F, 12, 10, 11);
      body_2.setRotationPoint(-6F, 5F, -3.5F);
      body_2.setTextureSize(64, 32);
      body_2.mirror = true;
      setRotation(body_2, 0F, 0F, 0F);
      mane = new ModelRenderer(this, 55, 150);
      mane.addBox(0F, 0F, 0F, 9, 6, 4);
      mane.setRotationPoint(-4.5F, 8F, -5F);
      mane.setTextureSize(64, 32);
      mane.mirror = true;
      setRotation(mane, 0F, 0F, 0F);
      snout = new ModelRenderer(this, 50, 131);
      snout.addBox(0F, 0F, 0F, 5, 2, 6);
      snout.setRotationPoint(-2.5F, 9F, -13F);
      snout.setTextureSize(64, 32);
      snout.mirror = true;
      setRotation(snout, 0.1745329F, 0F, 0F);
      snout_upper = new ModelRenderer(this, 50, 133);
      snout_upper.addBox(0F, 0F, 0F, 4, 2, 6);
      snout_upper.setRotationPoint(-2F, 8F, -13.1F);
      snout_upper.setTextureSize(64, 32);
      snout_upper.mirror = true;
      setRotation(snout_upper, 0.0872665F, 0F, 0F);
      Head_2 = new ModelRenderer(this, 50, 100);
      Head_2.addBox(0F, 0F, 0F, 7, 7, 5);
      Head_2.setRotationPoint(-3.5F, 6F, -9F);
      Head_2.setTextureSize(64, 32);
      Head_2.mirror = true;
      setRotation(Head_2, 0F, 0F, 0F);
      thigh = new ModelRenderer(this, 0, 35);
      thigh.addBox(-3F, 0F, 0F, 5, 8, 5);
      thigh.setRotationPoint(5F, 8F, 10F);
      thigh.setTextureSize(64, 32);
      thigh.mirror = true;
      setRotation(thigh, 0F, 0F, 0F);
      Teeth_3 = new ModelRenderer(this, 0, 115);
      Teeth_3.addBox(0F, 0F, 0F, 1, 2, 1);
      Teeth_3.setRotationPoint(1F, 12F, -12.3F);
      Teeth_3.setTextureSize(64, 32);
      Teeth_3.mirror = true;
      setRotation(Teeth_3, 0.0872665F, 0F, 0F);
      Teeth_4 = new ModelRenderer(this, 0, 115);
      Teeth_4.addBox(0F, 0F, 0F, 1, 2, 1);
      Teeth_4.setRotationPoint(-2F, 12F, -12.2F);
      Teeth_4.setTextureSize(64, 32);
      Teeth_4.mirror = true;
      setRotation(Teeth_4, 0.0872665F, 0F, 0F);
      thigh_2 = new ModelRenderer(this, 0, 35);
      thigh_2.addBox(0F, 0F, 0F, 5, 8, 5);
      thigh_2.setRotationPoint(-7F, 8F, 10F);
      thigh_2.setTextureSize(64, 32);
      thigh_2.mirror = true;
      setRotation(thigh_2, 0F, 0F, 0F);
      
      this.addChildTo(Leg3, thigh);
      this.addChildTo(Paw3, thigh);
      
      this.addChildTo(Leg4, thigh_2);
      this.addChildTo(Paw4, thigh_2);
      
      this.addChildTo(Leg2B, Leg2);
      this.addChildTo(Paw2, Leg2);

      this.addChildTo(Leg1B, Leg1);
      this.addChildTo(Paw1, Leg1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    if (this.isChild)
    {
        float var8 = 2.0F;
        GL11.glPushMatrix();
        GL11.glTranslatef(0.0F, 5.0F * f5, 2.0F * f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
        GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);

        Body.render(f5);
        Leg2.render(f5);
        //Leg2B.render(f5);
        //Paw3.render(f5);
        //Leg4.render(f5);
        //Paw2.render(f5);
        //Leg3.render(f5);
        Head.render(f5);
        JawB.render(f5);
        JawT.render(f5);
        Teeth2.render(f5);
        Teeth1.render(f5);
        Ear2.render(f5);
        Ear1.render(f5);
        Tail.render(f5);
        Leg1.render(f5);
       // Leg1B.render(f5);
        //Paw1.render(f5);
        //Paw4.render(f5);
        body_2.render(f5);
        mane.render(f5);
        snout.render(f5);
        snout_upper.render(f5);
        Head_2.render(f5);
        thigh.render(f5);
        Teeth_3.render(f5);
        Teeth_4.render(f5);
        thigh_2.render(f5);
        GL11.glPopMatrix();
        
    }
    else
    {
    Body.render(f5);
    Leg2.render(f5);
    //Leg2B.render(f5);
    //Paw3.render(f5);
    //Leg4.render(f5);
    //Paw2.render(f5);
    //Leg3.render(f5);
    Head.render(f5);
    JawB.render(f5);
    JawT.render(f5);
    Teeth2.render(f5);
    Teeth1.render(f5);
    Ear2.render(f5);
    Ear1.render(f5);
    Tail.render(f5);
    Leg1.render(f5);
   // Leg1B.render(f5);
    //Paw1.render(f5);
    //Paw4.render(f5);
    body_2.render(f5);
    mane.render(f5);
    snout.render(f5);
    snout_upper.render(f5);
    Head_2.render(f5);
    thigh.render(f5);
    Teeth_3.render(f5);
    Teeth_4.render(f5);
    thigh_2.render(f5);}
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    thigh.rotateAngleX = MathHelper.cos(f * 0.6662F) * 0.4F * f1;
    thigh_2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 0.4F * f1;
    
    Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 0.4F * f1;
    Leg1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 0.4F * f1;
    
  }

}
