// Date: 30.12.2012 15:02:35
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
@SideOnly(Side.CLIENT)
public class ModelBrontosaurus extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer FLeg1;
    ModelRenderer FLeg2;
    ModelRenderer BLeg1;
    ModelRenderer BLeg2;
    ModelRenderer Neck;
    ModelRenderer HeadB;
    ModelRenderer HeadT;
    ModelRenderer Tail;
    ModelRenderer Rug2;
    ModelRenderer Rug;
  
  public ModelBrontosaurus()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 51, 31, 73);
      Body.setRotationPoint(-13F, -36F, 0F);
      Body.setTextureSize(256, 256);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      FLeg1 = new ModelRenderer(this, 0, 15);
      FLeg1.addBox(0F, 0F, 0F, 10, 32, 10);
      FLeg1.setRotationPoint(28F, -8F, 0F);
      FLeg1.setTextureSize(256, 256);
      FLeg1.mirror = true;
      setRotation(FLeg1, 0F, 0F, 0F);
      FLeg2 = new ModelRenderer(this, 0, 15);
      FLeg2.addBox(0F, 0F, 0F, 10, 32, 10);
      FLeg2.setRotationPoint(-13F, -8F, 0F);
      FLeg2.setTextureSize(256, 256);
      FLeg2.mirror = true;
      setRotation(FLeg2, 0F, 0F, 0F);
      BLeg1 = new ModelRenderer(this, 0, 15);
      BLeg1.addBox(0F, 0F, 0F, 10, 32, 10);
      BLeg1.setRotationPoint(28F, -8F, 63F);
      BLeg1.setTextureSize(256, 256);
      BLeg1.mirror = true;
      setRotation(BLeg1, 0F, 0F, 0F);
      BLeg2 = new ModelRenderer(this, 0, 15);
      BLeg2.addBox(0F, 0F, 0F, 10, 32, 10);
      BLeg2.setRotationPoint(-13F, -8F, 63F);
      BLeg2.setTextureSize(256, 256);
      BLeg2.mirror = true;
      setRotation(BLeg2, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 0, 153);
      Neck.addBox(-2F, 0F, -45F, 12, 10, 93);
      Neck.setRotationPoint(8F, -73F, -15F);
      Neck.setTextureSize(256, 256);
      Neck.mirror = true;
      setRotation(Neck, -1.07818F, 0F, 0F);
      HeadB = new ModelRenderer(this, 0, 116);
      HeadB.addBox(0F, 0F, 0F, 18, 8, 23);
      HeadB.setRotationPoint(3F, -113F, -55F);
      HeadB.setTextureSize(256, 256);
      HeadB.mirror = true;
      setRotation(HeadB, 0F, 0F, 0F);
      HeadT = new ModelRenderer(this, 84, 127);
      HeadT.addBox(0F, 0F, 0F, 18, 7, 12);
      HeadT.setRotationPoint(3F, -120F, -44F);
      HeadT.setTextureSize(256, 256);
      HeadT.mirror = true;
      setRotation(HeadT, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 153);
      Tail.addBox(0F, 0F, 0F, 12, 10, 93);
      Tail.setRotationPoint(6F, -33F, 64F);
      Tail.setTextureSize(256, 256);
      Tail.mirror = true;
      setRotation(Tail, -0.3717861F, 0F, 0F);
      Rug2 = new ModelRenderer(this, 13, 16);
      Rug2.addBox(0F, 0F, 0F, 21, 7, 73);
      Rug2.setRotationPoint(2F, -50F, 0F);
      Rug2.setTextureSize(256, 256);
      Rug2.mirror = true;
      setRotation(Rug2, 0F, 0F, 0F);
      Rug = new ModelRenderer(this, 13, 16);
      Rug.addBox(0F, 0F, 0F, 41, 7, 73);
      Rug.setRotationPoint(-8F, -43F, 0F);
      Rug.setTextureSize(256, 256);
      Rug.mirror = true;
      setRotation(Rug, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    FLeg1.render(f5);
    FLeg2.render(f5);
    BLeg1.render(f5);
    BLeg2.render(f5);
    Neck.render(f5);
    HeadB.render(f5);
    HeadT.render(f5);
    Tail.render(f5);
    Rug2.render(f5);
    Rug.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    FLeg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    BLeg2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    BLeg1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    FLeg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
