// Date: 21.09.2013 19:18:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelHermitCrab extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape81;
    ModelRenderer Shape9;
    ModelRenderer Shape91;
    ModelRenderer Shape92;
    ModelRenderer Shape10;
    ModelRenderer Shape101;
    ModelRenderer Shape102;
    ModelRenderer Shape11;
    ModelRenderer Shape111;
    ModelRenderer Shape112;
    ModelRenderer Shape121;
    ModelRenderer Shape103;
    ModelRenderer Shape12;
    ModelRenderer Shape131;
    ModelRenderer Shape132;
    ModelRenderer Shape141;
    ModelRenderer Shape16;
    ModelRenderer Shape14;
    ModelRenderer Shape161;
  
  public ModelHermitCrab()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 11, 3, 11);
      Shape1.setRotationPoint(-8F, 16F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0.7679449F, 0F);
      Shape2 = new ModelRenderer(this, 0, 14);
      Shape2.addBox(0F, 0F, 0F, 9, 3, 9);
      Shape2.setRotationPoint(-6.5F, 13F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0.7679449F, 0F);
      Shape3 = new ModelRenderer(this, 0, 26);
      Shape3.addBox(0F, 0F, 0F, 7, 2, 7);
      Shape3.setRotationPoint(-5F, 11F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0.7679449F, 0F);
      Shape4 = new ModelRenderer(this, 0, 35);
      Shape4.addBox(0F, 0F, 0F, 5, 2, 5);
      Shape4.setRotationPoint(-3.5F, 9F, 0F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0.7679449F, 0F);
      Shape5 = new ModelRenderer(this, 0, 42);
      Shape5.addBox(0F, 0F, 0F, 3, 1, 3);
      Shape5.setRotationPoint(-2F, 8F, 0F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0.7679449F, 0F);
      Shape6 = new ModelRenderer(this, 44, 0);
      Shape6.addBox(0F, 0F, 0F, 11, 2, 10);
      Shape6.setRotationPoint(-5.5F, 19F, -5F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 107, 0);
      Shape7.addBox(0F, 0F, 0F, 3, 2, 2);
      Shape7.setRotationPoint(-1.5F, 19F, -7F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 86, 0);
      Shape8.addBox(0F, 0F, 0F, 5, 2, 1);
      Shape8.setRotationPoint(4.5F, 19F, -5.5F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0.7853982F, 0F);
      Shape81 = new ModelRenderer(this, 86, 0);
      Shape81.addBox(0F, 0F, 0F, 5, 2, 1);
      Shape81.setRotationPoint(-7.5F, 19F, -8.5F);
      Shape81.setTextureSize(128, 64);
      Shape81.mirror = true;
      setRotation(Shape81, 0F, -0.7853982F, 0F);
      Shape9 = new ModelRenderer(this, 101, 0);
      Shape9.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape9.setRotationPoint(-6.3F, 19F, -1F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0.3490659F);
      Shape91 = new ModelRenderer(this, 101, 0);
      Shape91.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape91.setRotationPoint(-6.3F, 19F, 2F);
      Shape91.setTextureSize(128, 64);
      Shape91.mirror = true;
      setRotation(Shape91, 0F, 0F, 0.3490659F);
      Shape92 = new ModelRenderer(this, 101, 0);
      Shape92.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape92.setRotationPoint(-6.3F, 19F, -4F);
      Shape92.setTextureSize(128, 64);
      Shape92.mirror = true;
      setRotation(Shape92, 0F, 0F, 0.3316126F);
      Shape10 = new ModelRenderer(this, 101, 4);
      Shape10.addBox(0F, 0F, 0F, 1, 3, 2);
      Shape10.setRotationPoint(-7F, 20.9F, -1F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0.0872665F);
      Shape101 = new ModelRenderer(this, 101, 4);
      Shape101.addBox(0F, 0F, 2F, 1, 3, 2);
      Shape101.setRotationPoint(-7F, 20.9F, 0F);
      Shape101.setTextureSize(128, 64);
      Shape101.mirror = true;
      setRotation(Shape101, 0F, 0F, 0.0523599F);
      Shape102 = new ModelRenderer(this, 101, 4);
      Shape102.addBox(0F, 0F, 0F, 1, 3, 2);
      Shape102.setRotationPoint(-7F, 20.9F, -4F);
      Shape102.setTextureSize(128, 64);
      Shape102.mirror = true;
      setRotation(Shape102, 0F, 0F, 0.0872665F);
      Shape11 = new ModelRenderer(this, 101, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape11.setRotationPoint(5.5F, 19.5F, -1F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, -0.3490659F);
      Shape111 = new ModelRenderer(this, 101, 0);
      Shape111.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape111.setRotationPoint(5.5F, 19.5F, 2F);
      Shape111.setTextureSize(128, 64);
      Shape111.mirror = true;
      setRotation(Shape111, 0F, 0F, -0.3490659F);
      Shape112 = new ModelRenderer(this, 101, 0);
      Shape112.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape112.setRotationPoint(5.5F, 19.5F, -4F);
      Shape112.setTextureSize(128, 64);
      Shape112.mirror = true;
      setRotation(Shape112, 0F, 0F, -0.3490659F);
      Shape121 = new ModelRenderer(this, 101, 4);
      Shape121.addBox(0F, 0F, 0F, 1, 3, 2);
      Shape121.setRotationPoint(6.1F, 21F, -1F);
      Shape121.setTextureSize(128, 64);
      Shape121.mirror = true;
      setRotation(Shape121, 0F, 0F, -0.0872665F);
      Shape103 = new ModelRenderer(this, 101, 4);
      Shape103.addBox(0F, 0F, 0F, 1, 3, 2);
      Shape103.setRotationPoint(6.1F, 21F, -4F);
      Shape103.setTextureSize(128, 64);
      Shape103.mirror = true;
      setRotation(Shape103, 0F, 0F, -0.0872665F);
      Shape12 = new ModelRenderer(this, 101, 4);
      Shape12.addBox(0F, 0F, 0F, 1, 3, 2);
      Shape12.setRotationPoint(6.1F, 21F, 2F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, -0.0872665F);
      Shape131 = new ModelRenderer(this, 107, 4);
      Shape131.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape131.setRotationPoint(-2F, 18F, -8.5F);
      Shape131.setTextureSize(128, 64);
      Shape131.mirror = true;
      setRotation(Shape131, -0.3717861F, 0.3490659F, 0.3346075F);
      Shape132 = new ModelRenderer(this, 107, 4);
      Shape132.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape132.setRotationPoint(1F, 18.5F, -8.9F);
      Shape132.setTextureSize(128, 64);
      Shape132.mirror = true;
      setRotation(Shape132, -0.3490659F, -0.3490659F, -0.3490659F);
      Shape141 = new ModelRenderer(this, 86, 3);
      Shape141.addBox(-1F, 0F, -4F, 3, 1, 4);
      Shape141.setRotationPoint(-7.5F, 20F, -7.5F);
      Shape141.setTextureSize(128, 64);
      Shape141.mirror = true;
      setRotation(Shape141, 0F, 0.3490659F, 0F);
      Shape16 = new ModelRenderer(this, 86, 9);
      Shape16.addBox(-1F, -1F, -4F, 3, 1, 4);
      Shape16.setRotationPoint(-7.5F, 20F, -8F);
      Shape16.setTextureSize(128, 64);
      Shape16.mirror = true;
      setRotation(Shape16, -0.3490659F, 0.3490659F, 0F);
      Shape14 = new ModelRenderer(this, 86, 3);
      Shape14.addBox(-1F, 0F, -4F, 3, 1, 4);
      Shape14.setRotationPoint(7.5F, 20F, -8F);
      Shape14.setTextureSize(128, 64);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, -0.3490659F, 0F);
      Shape161 = new ModelRenderer(this, 86, 9);
      Shape161.addBox(-1F, 0F, -3F, 3, 1, 4);
      Shape161.setRotationPoint(7.5F, 19F, -8.5F);
      Shape161.setTextureSize(128, 64);
      Shape161.mirror = true;
      setRotation(Shape161, -0.3490659F, -0.3490659F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape81.render(f5);
    Shape9.render(f5);
    Shape91.render(f5);
    Shape92.render(f5);
    Shape10.render(f5);
    Shape101.render(f5);
    Shape102.render(f5);
    Shape11.render(f5);
    Shape111.render(f5);
    Shape112.render(f5);
    Shape121.render(f5);
    Shape103.render(f5);
    Shape12.render(f5);
    Shape131.render(f5);
    Shape132.render(f5);
    Shape141.render(f5);
    Shape16.render(f5);
    Shape14.render(f5);
    Shape161.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.Shape10.rotateAngleX = MathHelper.cos(f * 5.1662F + (float)Math.PI) * 0.5F * f1;
    this.Shape101.rotateAngleX = MathHelper.cos(f * 5.1662F) * 0.5F * f1;
    this.Shape102.rotateAngleX = MathHelper.cos(f * 5.1662F + (float)Math.PI) * 0.5F * f1;
    this.Shape103.rotateAngleX = MathHelper.cos(f * 5.1662F) * 0.5F * f1;
    this.Shape12.rotateAngleX = MathHelper.cos(f * 5.1662F + (float)Math.PI) * 0.5F * f1;
    this.Shape121.rotateAngleX = MathHelper.cos(f * 5.1662F) * 0.5F * f1;
    
    this.Shape16.rotateAngleX = MathHelper.cos(f * 1.1662F + (float)Math.PI) * 0.8F * f1;
    this.Shape14.rotateAngleX = MathHelper.cos(f * 1.1662F) * 0.8F * f1;
    this.Shape16.rotateAngleX = MathHelper.cos(f * 1.1662F + (float)Math.PI) * 0.8F * f1;
    this.Shape14.rotateAngleX = MathHelper.cos(f * 1.1662F) * 0.8F * f1;
  }

}
