// Date: 01.08.2013 21:52:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelFishy extends ModelBase
{
  //fields
    ModelRenderer tailbeg;
    ModelRenderer tail1;
    ModelRenderer tailend;
    ModelRenderer body;
    ModelRenderer head;
  
  public ModelFishy()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      tailbeg = new ModelRenderer(this, 25, 0);
      tailbeg.addBox(0F, -1.5F, 0F, 1, 3, 1);
      tailbeg.setRotationPoint(2F, 22F, -2.5F);
      tailbeg.setTextureSize(64, 32);
      tailbeg.mirror = true;
      setRotation(tailbeg, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 20, 0);
      tail1.addBox(0F, -1F, 1F, 1, 2, 1);
      tail1.setRotationPoint(2F, 22F, -2.5F);
      tail1.setTextureSize(64, 32);
      tail1.mirror = true;
      setRotation(tail1, 0F, 0F, 0F);
      tailend = new ModelRenderer(this, 15, 0);
      tailend.addBox(0F, -2F, 2F, 1, 4, 1);
      tailend.setRotationPoint(2F, 22F, -2.5F);
      tailend.setTextureSize(64, 32);
      tailend.mirror = true;
      setRotation(tailend, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 0);
      body.addBox(0F, 0F, 0F, 1, 4, 4);
      body.setRotationPoint(2F, 20F, -6.5F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      head = new ModelRenderer(this, 30, 0);
      head.addBox(0F, 0F, 0F, 1, 3, 1);
      head.setRotationPoint(2F, 20.5F, -7.5F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    tailbeg.render(f5);
    tail1.render(f5);
    tailend.render(f5);
    body.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.tailend.rotateAngleY = MathHelper.cos(f * 0.3332F) * 0.8F * f1;    
  }

}
