// Date: 09.06.2014 12:11:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTanningRack extends ModelBase
{
  //fields
    ModelRenderer Shape2;
    ModelRenderer Shape1;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape6;
    ModelRenderer Shape5;
    ModelRenderer Shape8;
    ModelRenderer Shape7;
    ModelRenderer Shape12;
    ModelRenderer Shape11;
    ModelRenderer Shape10;
    ModelRenderer Shape9;
    ModelRenderer Shape13;
  
  public ModelTanningRack()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 14, 3, 1);
      Shape2.setRotationPoint(-7F, 19.4F, -7F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0.111544F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 14, 3, 1);
      Shape1.setRotationPoint(-7F, 18F, 6F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.1115358F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 3, 13);
      Shape3.setRotationPoint(-7F, 19.3F, -6F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0.111544F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 3, 13);
      Shape4.setRotationPoint(6F, 19.3F, -6F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0.111544F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape6.setRotationPoint(-7F, 22F, -6F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(6F, 22F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 0);
      Shape8.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape8.setRotationPoint(6F, 20F, 6F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape7.setRotationPoint(-7F, 20F, 6F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 34, 0);
      Shape12.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape12.setRotationPoint(6.2F, 20F, -5.2F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, -2.490967F, 0F);
      Shape11 = new ModelRenderer(this, 34, 0);
      Shape11.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape11.setRotationPoint(5.4F, 19F, 6.3F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 2.342252F, 0F);
      Shape10 = new ModelRenderer(this, 34, 0);
      Shape10.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape10.setRotationPoint(-6.2F, 19F, 5.7F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0.9294653F, 0F);
      Shape9 = new ModelRenderer(this, 34, 0);
      Shape9.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape9.setRotationPoint(-5.5F, 20F, -6.1F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, -0.8179294F, 0F);
      Shape13 = new ModelRenderer(this, 32, 0);
      Shape13.addBox(0F, 0F, -9F, 10, 0, 10);
      Shape13.setRotationPoint(-5F, 19.5F, 4F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0.111544F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape2.render(f5);
    Shape1.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape6.render(f5);
    Shape5.render(f5);
    Shape8.render(f5);
    Shape7.render(f5);
    Shape12.render(f5);
    Shape11.render(f5);
    Shape10.render(f5);
    Shape9.render(f5);
    Shape13.render(f5);
  }
  
  public void renderAll()
  {
	  	float f5 = 0.0625F;
	    Shape2.render(f5);
	    Shape1.render(f5);
	    Shape3.render(f5);
	    Shape4.render(f5);
	    Shape6.render(f5);
	    Shape5.render(f5);
	    Shape8.render(f5);
	    Shape7.render(f5);
	    Shape12.render(f5);
	    Shape11.render(f5);
	    Shape10.render(f5);
	    Shape9.render(f5);
	    Shape13.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
