// Date: 15.11.2012 20:55:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
public class ModelVulture extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape6;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer FootR;
    ModelRenderer FootL;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
  
  public ModelVulture()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 7, 0);
      Shape1.addBox(0F, 0F, 0F, 5, 4, 16);
      Shape1.setRotationPoint(-2F, 15F, -7F);
      Shape1.setTextureSize(128, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, -8, 24);
      Shape2.addBox(-20F, 0F, -4F, 20, 0, 8);
      Shape2.setRotationPoint(-2F, 16F, -1F);
      Shape2.setTextureSize(128, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 78, 24);
      Shape6.addBox(0F, 0F, -4F, 20, 0, 8);
      Shape6.setRotationPoint(3F, 16F, -1F);
      Shape6.setTextureSize(128, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 12);
      Shape3.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape3.setRotationPoint(0F, 17F, -12F);
      Shape3.setTextureSize(128, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 9);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape4.setRotationPoint(0F, 18F, -12F);
      Shape4.setTextureSize(128, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 57, 0);
      Shape5.addBox(0F, 0F, 0F, 3, 2, 3);
      Shape5.setRotationPoint(-1F, 16F, -10F);
      Shape5.setTextureSize(128, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      FootR = new ModelRenderer(this, 0, 0);
      FootR.addBox(0F, 0F, 0F, 1, 3, 1);
      FootR.setRotationPoint(-1F, 19F, 4F);
      FootR.setTextureSize(128, 32);
      FootR.mirror = true;
      setRotation(FootR, 0.6320364F, 0F, 0F);
      FootL = new ModelRenderer(this, 6, 0);
      FootL.addBox(0F, 0F, 0F, 1, 3, 1);
      FootL.setRotationPoint(1F, 19F, 4F);
      FootL.setTextureSize(128, 32);
      FootL.mirror = true;
      setRotation(FootL, 0.6320364F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 0, 21);
      Tail1.addBox(0F, 0F, 0F, 5, 0, 2);
      Tail1.setRotationPoint(-2F, 17F, 8F);
      Tail1.setTextureSize(128, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 18, 21);
      Tail2.addBox(0F, 0F, 0F, 7, 0, 2);
      Tail2.setRotationPoint(-3F, 17F, 10F);
      Tail2.setTextureSize(128, 32);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape6.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    FootR.render(f5);
    FootL.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Shape2.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    Shape6.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
  }

}
