// Date: 07.10.2012 15:37:11
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBird extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Beack;
    ModelRenderer WingR;
    ModelRenderer WingL;
  
  public ModelBird()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 3, 3, 7);
      Body.setRotationPoint(0F, 20F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Beack = new ModelRenderer(this, 5, 11);
      Beack.addBox(0F, 0F, 0F, 1, 1, 2);
      Beack.setRotationPoint(1F, 21F, -2F);
      Beack.setTextureSize(64, 32);
      Beack.mirror = true;
      setRotation(Beack, 0F, 0F, 0F);
      WingR = new ModelRenderer(this, 22, 7);
      WingR.addBox(-5F, 0F, -3F, 5, 1, 5);
      WingR.setRotationPoint(0F, 21F, 4F);
      WingR.setTextureSize(64, 32);
      WingR.mirror = true;
      setRotation(WingR, 0F, 0F, 0F);
      WingL = new ModelRenderer(this, 22, 0);
      WingL.addBox(0F, 0F, -2F, 5, 1, 5);
      WingL.setRotationPoint(3F, 21F, 3F);
      WingL.setTextureSize(64, 32);
      WingL.mirror = true;
      setRotation(WingL, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Beack.render(f5);
    WingR.render(f5);
    WingL.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.WingR.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    this.WingL.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
