// Date: 06.06.2014 20:15:54
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDeerArmor extends ModelBiped
{
  //fields
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelDeerArmor(float f)
  {
	  super(f, 0, 64, 64);
    textureWidth = 64;
    textureHeight = 64;
      Shape3 = new ModelRenderer(this, 0, 38);
      Shape3.addBox(-5F, -10F, -1F, 1, 3, 1);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 43);
      Shape4.addBox(-6F, -15F, -1F, 1, 7, 1);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 33);
      Shape1.addBox(4F, -10F, -1F, 1, 3, 1);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 52);
      Shape2.addBox(5F, -15F, -1F, 1, 7, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      
      this.bipedHead.addChild(Shape1);
      this.bipedHead.addChild(Shape2);
      this.bipedHead.addChild(Shape3);
      this.bipedHead.addChild(Shape4);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  

}
