// Date: 12.11.2012 21:42:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;


@SideOnly(Side.CLIENT)
public class ModelElephant extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Leg2;
    ModelRenderer Leg4;
    ModelRenderer Leg1;
    ModelRenderer Leg3;
    ModelRenderer Belly;
    ModelRenderer Head;
    ModelRenderer EarR;
    ModelRenderer EarL;
    ModelRenderer Nose;
    ModelRenderer Tail;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelElephant()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 37, 29, 47);
      Body.setRotationPoint(-17F, -26F, 0F);
      Body.setTextureSize(256, 256);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 6, 23, 6);
      Leg2.setRotationPoint(-17F, 1F, 0F);
      Leg2.setTextureSize(256, 256);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(0F, 0F, 0F, 6, 23, 6);
      Leg4.setRotationPoint(-17F, 1F, 41F);
      Leg4.setTextureSize(256, 256);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 6, 23, 6);
      Leg1.setRotationPoint(14F, 1F, 0F);
      Leg1.setTextureSize(256, 256);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(0F, 0F, 0F, 6, 23, 6);
      Leg3.setRotationPoint(14F, 1F, 41F);
      Leg3.setTextureSize(256, 256);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Belly = new ModelRenderer(this, 0, 186);
      Belly.addBox(0F, 0F, 0F, 42, 35, 32);
      Belly.setRotationPoint(-20F, -28F, 8F);
      Belly.setTextureSize(256, 256);
      Belly.mirror = true;
      setRotation(Belly, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 172, 0);
      Head.addBox(0F, 0F, 0F, 23, 18, 15);
      Head.setRotationPoint(-10F, -29F, -15F);
      Head.setTextureSize(256, 256);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      EarR = new ModelRenderer(this, 130, 21);
      EarR.addBox(-15F, 0F, 0F, 15, 12, 0);
      EarR.setRotationPoint(13F, -28F, -12F);
      EarR.setTextureSize(256, 256);
      EarR.mirror = true;
      setRotation(EarR, 0F, 2.472381F, 0F);
      EarL = new ModelRenderer(this, 130, 0);
      EarL.addBox(-15F, 0F, 0F, 15, 12, 0);
      EarL.setRotationPoint(-10F, -28F, -12F);
      EarL.setTextureSize(256, 256);
      EarL.mirror = true;
      setRotation(EarL, 0F, 0.669215F, 0F);
      Nose = new ModelRenderer(this, 0, 85);
      Nose.addBox(0F, 0F, 0F, 7, 35, 4);
      Nose.setRotationPoint(-2F, -18F, -14F);
      Nose.setTextureSize(256, 256);
      Nose.mirror = true;
      setRotation(Nose, -0.7435722F, 0F, 0F);
      Tail = new ModelRenderer(this, 29, 0);
      Tail.addBox(0F, 0F, 0F, 3, 15, 1);
      Tail.setRotationPoint(0F, -18F, 45F);
      Tail.setTextureSize(256, 256);
      Tail.mirror = true;
      setRotation(Tail, 0.5576792F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 100, 100);
      Shape1.addBox(0F, 0F, 0F, 2, 2, 14);
      Shape1.setRotationPoint(8F, -5F, -26F);
      Shape1.setTextureSize(256, 256);
      Shape1.mirror = true;
      setRotation(Shape1, 0.5948578F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 100, 100);
      Shape2.addBox(0F, 0F, 0F, 2, 2, 14);
      Shape2.setRotationPoint(-7F, -5F, -26F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0.5948578F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    if (this.isChild)
    {
        float var8 = 2.0F;
        GL11.glPushMatrix();
        GL11.glTranslatef(0.0F, 5.0F * f5, 2.0F * f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
        GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
        Body.render(f5);
        Leg2.render(f5);
        Leg4.render(f5);
        Leg1.render(f5);
        Leg3.render(f5);
        Belly.render(f5);
        Head.render(f5);
        EarR.render(f5);
        EarL.render(f5);
        Nose.render(f5);
        Tail.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
        GL11.glPopMatrix();
        
    }
    else
    {
    
    Body.render(f5);
    Leg2.render(f5);
    Leg4.render(f5);
    Leg1.render(f5);
    Leg3.render(f5);
    Belly.render(f5);
    Head.render(f5);
    EarR.render(f5);
    EarL.render(f5);
    Nose.render(f5);
    Tail.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg3.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    Leg4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    
  }

}
