// Date: 30.08.2014 21:37:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import com.lom.lotsomobsentity.EntityMole;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.init.Blocks;
import net.minecraft.util.MathHelper;

public class ModelMole extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Body;
    ModelRenderer ArmR;
    ModelRenderer ArmL;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer Shape4;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape5;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    
    ModelRenderer Body1;
    ModelRenderer ArmR1;
    ModelRenderer ArmL1;
    ModelRenderer Head1;
    ModelRenderer Nose1;
    ModelRenderer ArmL2;
    ModelRenderer ArmR2;
    ModelRenderer Shape11;
  
  public ModelMole()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 8, 2, 8);
      Shape1.setRotationPoint(-4F, 22F, -4F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 6, 2, 6);
      Shape2.setRotationPoint(-3F, 20F, -3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 4, 1, 4);
      Shape3.setRotationPoint(-2F, 19F, -2F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 25);
      Body.addBox(0F, 0F, 0F, 3, 3, 3);
      Body.setRotationPoint(-1.5F, 17F, -1.5F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      ArmR = new ModelRenderer(this, 16, 13);
      ArmR.addBox(0F, 0F, 0F, 3, 1, 1);
      ArmR.setRotationPoint(1F, 17F, -1F);
      ArmR.setTextureSize(64, 32);
      ArmR.mirror = true;
      setRotation(ArmR, 0F, 0.4089647F, 0.2974289F);
      ArmL = new ModelRenderer(this, 0, 13);
      ArmL.addBox(-3F, 0F, 0F, 3, 1, 1);
      ArmL.setRotationPoint(-1F, 17F, -1F);
      ArmL.setTextureSize(64, 32);
      ArmL.mirror = true;
      setRotation(ArmL, 0F, -0.4461433F, -0.4089647F);
      Head = new ModelRenderer(this, 0, 17);
      Head.addBox(0F, 0F, 0F, 2, 2, 3);
      Head.setRotationPoint(-1F, 15F, -2.52F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 24, 24);
      Nose.addBox(0F, 0F, 0F, 1, 1, 1);
      Nose.setRotationPoint(-0.5F, 16F, -3F);
      Nose.setTextureSize(64, 32);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 11, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape4.setRotationPoint(4F, 23F, -2F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 8, 0);
      Shape6.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape6.setRotationPoint(0F, 23F, -5F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 7);
      Shape7.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape7.setRotationPoint(1F, 23F, 4F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 9, 0);
      Shape8.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape8.setRotationPoint(-3F, 23F, 4F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 7, 2);
      Shape5.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape5.setRotationPoint(-5F, 23F, -5F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 11, 3);
      Shape9.addBox(0F, 0F, 0F, 4, 1, 2);
      Shape9.setRotationPoint(2F, 23F, 3F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 10, 2);
      Shape10.addBox(0F, 0F, 0F, 3, 1, 2);
      Shape10.setRotationPoint(-6F, 23F, 1F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      
      
      
      Body1 = new ModelRenderer(this, 35, 21);
      Body1.addBox(0F, 0F, 0F, 3, 6, 3);
      Body1.setRotationPoint(-1.5F, 23F, -0.5F);
      Body1.setTextureSize(64, 32);
      Body1.mirror = true;
      setRotation(Body1, 1.570796F, 0F, 0F);
      ArmR1 = new ModelRenderer(this, 16, 18);
      ArmR1.addBox(0F, 0F, 0F, 2, 1, 1);
      ArmR1.setRotationPoint(1F, 22F, 4F);
      ArmR1.setTextureSize(64, 32);
      ArmR1.mirror = true;
      setRotation(ArmR1, -0.0371786F, 0F, 0.8922867F);
      ArmL1 = new ModelRenderer(this, 16, 18);
      ArmL1.addBox(-2F, 0F, 0F, 2, 1, 1);
      ArmL1.setRotationPoint(-1F, 22F, 4F);
      ArmL1.setTextureSize(64, 32);
      ArmL1.mirror = true;
      setRotation(ArmL1, -0.0743572F, 0F, -0.669215F);
      Head1 = new ModelRenderer(this, 0, 17);
      Head1.addBox(0F, 0F, 0F, 2, 2, 3);
      Head1.setRotationPoint(-1F, 20.5F, -2.52F);
      Head1.setTextureSize(64, 32);
      Head1.mirror = true;
      setRotation(Head1, 0F, 0F, 0F);
      Nose1 = new ModelRenderer(this, 24, 24);
      Nose1.addBox(0F, 0F, 0F, 1, 1, 1);
      Nose1.setRotationPoint(-0.5F, 21.5F, -3F);
      Nose1.setTextureSize(64, 32);
      Nose1.mirror = true;
      setRotation(Nose1, 0F, 0F, 0F);
      ArmL2 = new ModelRenderer(this, 16, 18);
      ArmL2.addBox(-2F, 0F, 0F, 2, 1, 1);
      ArmL2.setRotationPoint(-1F, 22F, 0F);
      ArmL2.setTextureSize(64, 32);
      ArmL2.mirror = true;
      setRotation(ArmL2, 0F, -0.4461433F, -0.6320364F);
      ArmR2 = new ModelRenderer(this, 16, 18);
      ArmR2.addBox(0F, 0F, 0F, 2, 1, 1);
      ArmR2.setRotationPoint(1F, 22F, 0F);
      ArmR2.setTextureSize(64, 32);
      ArmR2.mirror = true;
      setRotation(ArmR2, -0.0371786F, 0.3717861F, 0.8922867F);
      Shape11 = new ModelRenderer(this, 50, 20);
      Shape11.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape11.setRotationPoint(-0.5F, 21F, 5F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    EntityMole Mole = (EntityMole)entity;
    
    
    if(Mole.worldObj.getBlock((int)Mole.posX,(int) Mole.posY - 1, (int)Mole.posZ) == Blocks.dirt || Mole.worldObj.getBlock((int)Mole.posX, (int)Mole.posY - 1, (int)Mole.posZ) == Blocks.grass|| Mole.worldObj.getBlock((int)Mole.posX, (int)Mole.posY - 1, (int)Mole.posZ) == Blocks.sand)
    {
    if(!Mole.isSprinting())
    {
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Body.render(f5);
    ArmR.render(f5);
    ArmL.render(f5);
    Head.render(f5);
    Nose.render(f5);
    Shape4.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape5.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    }
    else
    {
        Shape4.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape5.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
    }
    }
    else
    {
        Body1.render(f5);
        ArmR1.render(f5);
        ArmL1.render(f5);
        Head1.render(f5);
        Nose1.render(f5);
        ArmL2.render(f5);
        ArmR2.render(f5);
        Shape11.render(f5);
    }
    }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null); 
    ArmL1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    ArmR1.rotateAngleX = MathHelper.cos(f * 0.6662F ) * 1.4F * f1;
    ArmL2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    ArmR2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
  }

}
