// Date: 03.04.2013 18:57:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
public class ModelEasterBunny extends ModelBase
{
  //fields
    ModelRenderer big_foot_2;
    ModelRenderer big_foot_;
    ModelRenderer hip_2;
    ModelRenderer hip;
    ModelRenderer shin;
    ModelRenderer shin_2;
    ModelRenderer body_back;
    ModelRenderer body;
    ModelRenderer leg_2;
    ModelRenderer leg;
    ModelRenderer fur;
    ModelRenderer head;
    ModelRenderer ear;
    ModelRenderer ear_2;
    ModelRenderer snout;
    ModelRenderer nose;
    ModelRenderer teeth;
    ModelRenderer tail;
    ModelRenderer neck;
    ModelRenderer basket;
    ModelRenderer basket_handle;
    ModelRenderer basket_handle_2;
    ModelRenderer basket_handle_top;
  
  public ModelEasterBunny()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      big_foot_2 = new ModelRenderer(this, 60, 50);
      big_foot_2.addBox(0F, 0F, 0F, 2, 1, 5);
      big_foot_2.setRotationPoint(0.5F, 23F, 0.5F);
      big_foot_2.setTextureSize(64, 32);
      big_foot_2.mirror = true;
      setRotation(big_foot_2, 0F, 0F, 0F);
      big_foot_ = new ModelRenderer(this, 42, 50);
      big_foot_.addBox(0F, 0F, 0F, 2, 1, 5);
      big_foot_.setRotationPoint(-3.5F, 23F, 0.5F);
      big_foot_.setTextureSize(64, 32);
      big_foot_.mirror = true;
      setRotation(big_foot_, 0F, 0F, 0F);
      hip_2 = new ModelRenderer(this, 60, 32);
      hip_2.addBox(0F, 0F, 0F, 2, 3, 4);
      hip_2.setRotationPoint(0.5F, 19.5F, 2.3F);
      hip_2.setTextureSize(64, 32);
      hip_2.mirror = true;
      setRotation(hip_2, 0.0872665F, 0F, 0F);
      hip = new ModelRenderer(this, 42, 32);
      hip.addBox(0F, 0F, 0F, 2, 3, 4);
      hip.setRotationPoint(-3.5F, 19.5F, 2.333333F);
      hip.setTextureSize(64, 32);
      hip.mirror = true;
      setRotation(hip, 0.0872665F, 0F, 0F);
      shin = new ModelRenderer(this, 42, 42);
      shin.addBox(0F, 0F, 0F, 2, 2, 3);
      shin.setRotationPoint(-3.5F, 21F, 3F);
      shin.setTextureSize(64, 32);
      shin.mirror = true;
      setRotation(shin, 0F, 0F, 0F);
      shin_2 = new ModelRenderer(this, 60, 42);
      shin_2.addBox(0F, 0F, 0F, 2, 2, 3);
      shin_2.setRotationPoint(0.5F, 21F, 3F);
      shin_2.setTextureSize(64, 32);
      shin_2.mirror = true;
      setRotation(shin_2, 0F, 0F, 0F);
      body_back = new ModelRenderer(this, 0, 30);
      body_back.addBox(0F, 0F, 0F, 4, 2, 7);
      body_back.setRotationPoint(-2.5F, 15F, 5.7F);
      body_back.setTextureSize(64, 32);
      body_back.mirror = true;
      setRotation(body_back, -1.48353F, 0F, 0F);
      body = new ModelRenderer(this, 0, 43);
      body.addBox(0F, 0F, 0F, 4, 3, 7);
      body.setRotationPoint(-2.5F, 15F, 5.2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, -1.48353F, 0F, 0F);
      leg_2 = new ModelRenderer(this, 20, 15);
      leg_2.addBox(0F, 0F, 0F, 1, 5, 2);
      leg_2.setRotationPoint(1.5F, 15.2F, 4.5F);
      leg_2.setTextureSize(64, 32);
      leg_2.mirror = true;
      setRotation(leg_2, -0.9599311F, 0F, 0F);
      leg = new ModelRenderer(this, 30, 15);
      leg.addBox(0F, 0F, 0F, 1, 5, 2);
      leg.setRotationPoint(-3.5F, 15.2F, 4.5F);
      leg.setTextureSize(64, 32);
      leg.mirror = true;
      setRotation(leg, -0.9599311F, 0F, 0F);
      fur = new ModelRenderer(this, 0, 57);
      fur.addBox(0F, 0F, 0F, 3, 2, 6);
      fur.setRotationPoint(-2F, 15.3F, 4F);
      fur.setTextureSize(64, 32);
      fur.mirror = true;
      setRotation(fur, -1.48353F, 0F, 0F);
      head = new ModelRenderer(this, 41, 0);
      head.addBox(0F, 0F, 0F, 3, 3, 3);
      head.setRotationPoint(-2F, 12F, 2.3F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      ear = new ModelRenderer(this, 67, 0);
      ear.addBox(0F, 0F, 0F, 1, 4, 1);
      ear.setRotationPoint(0F, 9.4F, 3.8F);
      ear.setTextureSize(64, 32);
      ear.mirror = true;
      setRotation(ear, 0.0872665F, 0F, 0F);
      ear_2 = new ModelRenderer(this, 67, 0);
      ear_2.addBox(0F, 0F, 0F, 1, 4, 1);
      ear_2.setRotationPoint(-1.966667F, 9.4F, 3.8F);
      ear_2.setTextureSize(64, 32);
      ear_2.mirror = true;
      setRotation(ear_2, 0.0872665F, 0F, 0F);
      snout = new ModelRenderer(this, 56, 0);
      snout.addBox(0F, 0F, 0F, 2, 2, 1);
      snout.setRotationPoint(-1.5F, 12.9F, 1.5F);
      snout.setTextureSize(64, 32);
      snout.mirror = true;
      setRotation(snout, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 33, 0);
      nose.addBox(0F, 0F, 0F, 1, 1, 1);
      nose.setRotationPoint(-1F, 13F, 1.4F);
      nose.setTextureSize(64, 32);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      teeth = new ModelRenderer(this, 16, 0);
      teeth.addBox(0F, 0F, 0F, 1, 1, 0);
      teeth.setRotationPoint(-1F, 14.3F, 2.1F);
      teeth.setTextureSize(64, 32);
      teeth.mirror = true;
      setRotation(teeth, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 21, 0);
      tail.addBox(0F, 0F, 0F, 2, 3, 1);
      tail.setRotationPoint(-1.5F, 19.8F, 4.8F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 0.6457718F, 0F, 0F);
      neck = new ModelRenderer(this, 0, 0);
      neck.addBox(0F, 0F, 0F, 3, 1, 3);
      neck.setRotationPoint(-2F, 15F, 2.3F);
      neck.setTextureSize(64, 32);
      neck.mirror = true;
      setRotation(neck, 0.0872665F, 0F, 0F);
      basket = new ModelRenderer(this, 90, 0);
      basket.addBox(0F, 0F, 0F, 4, 3, 3);
      basket.setRotationPoint(0F, 19.3F, -0.8F);
      basket.setTextureSize(64, 32);
      basket.mirror = true;
      setRotation(basket, -0.2617994F, 0F, 0F);
      basket_handle = new ModelRenderer(this, 90, 11);
      basket_handle.addBox(0F, 0F, 0F, 1, 2, 1);
      basket_handle.setRotationPoint(2.4F, 18.4F, 0.5F);
      basket_handle.setTextureSize(64, 32);
      basket_handle.mirror = true;
      setRotation(basket_handle, -0.2617994F, 0F, 0F);
      basket_handle_2 = new ModelRenderer(this, 90, 18);
      basket_handle_2.addBox(0F, 0F, 0F, 1, 2, 1);
      basket_handle_2.setRotationPoint(0.6F, 18.4F, 0.5F);
      basket_handle_2.setTextureSize(64, 32);
      basket_handle_2.mirror = true;
      setRotation(basket_handle_2, -0.2617994F, 0F, 0F);
      basket_handle_top = new ModelRenderer(this, 90, 25);
      basket_handle_top.addBox(0F, 0F, 0F, 2, 1, 1);
      basket_handle_top.setRotationPoint(1F, 18.2F, 0.5F);
      basket_handle_top.setTextureSize(64, 32);
      basket_handle_top.mirror = true;
      setRotation(basket_handle_top, -0.2617994F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    big_foot_2.render(f5);
    big_foot_.render(f5);
    hip_2.render(f5);
    hip.render(f5);
    shin.render(f5);
    shin_2.render(f5);
    body_back.render(f5);
    body.render(f5);
    leg_2.render(f5);
    leg.render(f5);
    fur.render(f5);
    head.render(f5);
    ear.render(f5);
    ear_2.render(f5);
    snout.render(f5);
    nose.render(f5);
    teeth.render(f5);
    tail.render(f5);
    neck.render(f5);
    basket.render(f5);
    basket_handle.render(f5);
    basket_handle_2.render(f5);
    basket_handle_top.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
