// Date: 14.07.2014 11:50:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelNarwal extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Horn;
    ModelRenderer Fin2;
    ModelRenderer Fin1;
    ModelRenderer TailC;
    ModelRenderer Tail;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelNarwal()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Body = new ModelRenderer(this, 5, 0);
      Body.addBox(0F, 0F, 0F, 12, 7, 20);
      Body.setRotationPoint(-6F, 15F, 0F);
      Body.setTextureSize(128, 128);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Horn = new ModelRenderer(this, 0, 66);
      Horn.addBox(0F, 0F, 0F, 2, 2, 15);
      Horn.setRotationPoint(-1F, 18F, -20F);
      Horn.setTextureSize(128, 128);
      Horn.mirror = true;
      setRotation(Horn, 0F, 0F, 0F);
      Fin2 = new ModelRenderer(this, 58, 0);
      Fin2.addBox(-7F, 0F, -2F, 8, 1, 5);
      Fin2.setRotationPoint(-6F, 20F, 9F);
      Fin2.setTextureSize(128, 128);
      Fin2.mirror = true;
      setRotation(Fin2, 0.3346075F, 0.3717861F, 0F);
      Fin1 = new ModelRenderer(this, 58, 12);
      Fin1.addBox(-1F, 0F, -2F, 8, 1, 5);
      Fin1.setRotationPoint(6F, 20F, 9F);
      Fin1.setTextureSize(128, 128);
      Fin1.mirror = true;
      setRotation(Fin1, 0.3346145F, -0.37179F, 0F);
      TailC = new ModelRenderer(this, 0, 0);
      TailC.addBox(-3F, 1F, 8F, 6, 3, 7);
      TailC.setRotationPoint(0F, 16F, 20F);
      TailC.setTextureSize(128, 128);
      TailC.mirror = true;
      setRotation(TailC, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 44, 40);
      Tail.addBox(-10F, 2F, 14F, 20, 1, 8);
      Tail.setRotationPoint(0F, 16F, 20F);
      Tail.setTextureSize(128, 128);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 44);
      Shape1.addBox(0F, 0F, -6F, 3, 3, 6);
      Shape1.setRotationPoint(-1.5F, 17.5F, 0F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 72, 25);
      Shape2.addBox(-5F, 0F, 0F, 10, 5, 9);
      Shape2.setRotationPoint(0F, 16F, 20F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Horn.render(f5);
    Fin2.render(f5);
    Fin1.render(f5);
    TailC.render(f5);
    Tail.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.Shape2.rotateAngleX = MathHelper.cos(f * 0.3332F) * 0.6F * f1;

    this.TailC.rotateAngleX = MathHelper.cos(f * 0.3332F) * 0.8F * f1;

    this.Tail.rotateAngleX = MathHelper.cos(f * 0.3332F) * 0.9F * f1;
    
    this.Fin1.rotateAngleY = MathHelper.cos(f * 0.3332F) * .4F * f1;
    this.Fin2.rotateAngleY = MathHelper.cos(f * 0.3332F + (float)Math.PI) * .4F * f1;    
  }

}
