// Date: 30.12.2012 13:52:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import org.lwjgl.opengl.GL11;

import com.lom.lotsomobsentity.EntityTriceratops;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
@SideOnly(Side.CLIENT)
public class ModelTriceratops extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Leg2;
    ModelRenderer Leg4;
    ModelRenderer Leg1;
    ModelRenderer Leg3;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer HornNose;
    ModelRenderer HeadPlate;
    ModelRenderer HornPlateR;
    ModelRenderer HornPlateL;
    ModelRenderer Rug;
    ModelRenderer Tail;
    ModelRenderer TailM;
  
    ModelRenderer Body1;
    ModelRenderer Leg21;
    ModelRenderer Leg41;
    ModelRenderer Leg11;
    ModelRenderer Leg31;
    ModelRenderer Head1;
    ModelRenderer Nose1;
    ModelRenderer HornNose1;
    ModelRenderer HeadPlate1;
    ModelRenderer HornPlateR1;
    ModelRenderer HornPlateL1;
    ModelRenderer Rug1;
    ModelRenderer Tail1;
    ModelRenderer TailM1;
  public ModelTriceratops()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 32, 18, 48);
      Body.setRotationPoint(-16F, -6F, 0F);
      Body.setTextureSize(512, 512);
      Body.mirror = true;
      setRotation(Body, 0.0436332F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg2.setRotationPoint(-15F, 10F, 1F);
      Leg2.setTextureSize(512, 512);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg4.setRotationPoint(-15F, 10F, 42F);
      Leg4.setTextureSize(512, 512);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg1.setRotationPoint(9F, 10F, 1F);
      Leg1.setTextureSize(512, 512);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg3.setRotationPoint(9F, 10F, 42F);
      Leg3.setTextureSize(512, 512);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 150);
      Head.addBox(0F, 0F, -1F, 20, 12, 16);
      Head.setRotationPoint(-10F, -8F, -15F);
      Head.setTextureSize(512, 512);
      Head.mirror = true;
      setRotation(Head, 0.1858931F, 0F, 0F);
      Nose = new ModelRenderer(this, 0, 125);
      Nose.addBox(0F, 0F, 0F, 9, 5, 11);
      Nose.setRotationPoint(-5F, -1F, -25F);
      Nose.setTextureSize(512, 512);
      Nose.mirror = true;
      setRotation(Nose, 0.0743592F, 0F, 0F);
      HornNose = new ModelRenderer(this, 0, 100);
      HornNose.addBox(0F, 0F, 0F, 3, 4, 3);
      HornNose.setRotationPoint(-2F, -5F, -23F);
      HornNose.setTextureSize(512, 512);
      HornNose.mirror = true;
      setRotation(HornNose, 0F, 0F, 0F);
      HeadPlate = new ModelRenderer(this, 0, 186);
      HeadPlate.addBox(0F, 0F, 0F, 34, 28, 2);
      HeadPlate.setRotationPoint(-17F, -22F, 2F);
      HeadPlate.setTextureSize(512, 512);
      HeadPlate.mirror = true;
      setRotation(HeadPlate, -0.2519884F, 0F, 0F);
      HornPlateR = new ModelRenderer(this, 0, 224);
      HornPlateR.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateR.setRotationPoint(-14F, -16F, 1F);
      HornPlateR.setTextureSize(512, 512);
      HornPlateR.mirror = true;
      setRotation(HornPlateR, -1.970466F, 0F, 0F);
      HornPlateL = new ModelRenderer(this, 0, 224);
      HornPlateL.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateL.setRotationPoint(11F, -16F, 1F);
      HornPlateL.setTextureSize(512, 512);
      HornPlateL.mirror = true;
      setRotation(HornPlateL, -1.970466F, 0F, 0F);
      Rug = new ModelRenderer(this, 168, 0);
      Rug.addBox(0F, 0F, 0F, 20, 7, 43);
      Rug.setRotationPoint(-10F, -13F, 0F);
      Rug.setTextureSize(512, 512);
      Rug.mirror = true;
      setRotation(Rug, 0.0436332F, 0F, 0F);
      Tail = new ModelRenderer(this, 310, 0);
      Tail.addBox(0F, 0F, 0F, 20, 10, 28);
      Tail.setRotationPoint(-10F, -14F, 42F);
      Tail.setTextureSize(512, 512);
      Tail.mirror = true;
      setRotation(Tail, -0.2974289F, 0F, 0F);
      TailM = new ModelRenderer(this, 435, 0);
      TailM.addBox(0F, 0F, 0F, 14, 6, 18);
      TailM.setRotationPoint(-7F, -2F, 65F);
      TailM.setTextureSize(512, 512);
      TailM.mirror = true;
      setRotation(TailM, 0.0743572F, 0F, 0F);
      
      
      
      Body1 = new ModelRenderer(this, 0, 0);
      Body1.addBox(0F, 0F, 0F, 32, 18, 48);
      Body1.setRotationPoint(-16F, -6F, 0F);
      Body1.setTextureSize(512, 512);
      Body1.mirror = true;
      setRotation(Body1, -0.1794384F, 0F, 0F);
      Leg21 = new ModelRenderer(this, 0, 0);
      Leg21.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg21.setRotationPoint(-15F, 10F, 1F);
      Leg21.setTextureSize(512, 512);
      Leg21.mirror = true;
      setRotation(Leg21, 0F, 0F, 0F);
      Leg41 = new ModelRenderer(this, 0, 0);
      Leg41.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg41.setRotationPoint(-15F, 17F, 42F);
      Leg41.setTextureSize(512, 512);
      Leg41.mirror = true;
      setRotation(Leg41, -1.449967F, 0F, 0F);
      Leg11 = new ModelRenderer(this, 0, 0);
      Leg11.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg11.setRotationPoint(9F, 10F, 1F);
      Leg11.setTextureSize(512, 512);
      Leg11.mirror = true;
      setRotation(Leg11, 0F, 0F, 0F);
      Leg31 = new ModelRenderer(this, 0, 0);
      Leg31.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg31.setRotationPoint(9F, 17F, 42F);
      Leg31.setTextureSize(512, 512);
      Leg31.mirror = true;
      setRotation(Leg31, -1.449966F, 0F, 0F);
      Head1 = new ModelRenderer(this, 0, 150);
      Head1.addBox(0F, 0F, -1F, 20, 12, 16);
      Head1.setRotationPoint(-10F, -8F, -15F);
      Head1.setTextureSize(512, 512);
      Head1.mirror = true;
      setRotation(Head1, 0.1858931F, 0F, 0F);
      Nose1 = new ModelRenderer(this, 0, 125);
      Nose1.addBox(0F, 0F, 0F, 9, 5, 11);
      Nose1.setRotationPoint(-5F, -1F, -25F);
      Nose1.setTextureSize(512, 512);
      Nose1.mirror = true;
      setRotation(Nose1, 0.0743592F, 0F, 0F);
      HornNose1 = new ModelRenderer(this, 0, 100);
      HornNose1.addBox(0F, 0F, 0F, 3, 4, 3);
      HornNose1.setRotationPoint(-2F, -5F, -23F);
      HornNose1.setTextureSize(512, 512);
      HornNose1.mirror = true;
      setRotation(HornNose1, 0F, 0F, 0F);
      HeadPlate1 = new ModelRenderer(this, 0, 186);
      HeadPlate1.addBox(0F, 0F, 0F, 34, 28, 2);
      HeadPlate1.setRotationPoint(-17F, -22F, 2F);
      HeadPlate1.setTextureSize(512, 512);
      HeadPlate1.mirror = true;
      setRotation(HeadPlate1, -0.2519884F, 0F, 0F);
      HornPlateR1 = new ModelRenderer(this, 0, 224);
      HornPlateR1.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateR1.setRotationPoint(-14F, -16F, 1F);
      HornPlateR1.setTextureSize(512, 512);
      HornPlateR1.mirror = true;
      setRotation(HornPlateR1, -1.970466F, 0F, 0F);
      HornPlateL1 = new ModelRenderer(this, 0, 224);
      HornPlateL1.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateL1.setRotationPoint(11F, -16F, 1F);
      HornPlateL1.setTextureSize(512, 512);
      HornPlateL1.mirror = true;
      setRotation(HornPlateL1, -1.970466F, 0F, 0F);
      Rug1 = new ModelRenderer(this, 168, 0);
      Rug1.addBox(0F, 0F, 0F, 20, 7, 43);
      Rug1.setRotationPoint(-10F, -13F, 0F);
      Rug1.setTextureSize(512, 512);
      Rug1.mirror = true;
      setRotation(Rug1, -0.1794373F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 310, 0);
      Tail1.addBox(0F, 0F, 0F, 20, 10, 28);
      Tail1.setRotationPoint(-10F, -5F, 42F);
      Tail1.setTextureSize(512, 512);
      Tail1.mirror = true;
      setRotation(Tail1, -0.6320364F, 0F, 0F);
      TailM1 = new ModelRenderer(this, 435, 0);
      TailM1.addBox(0F, 0F, 0F, 14, 6, 18);
      TailM1.setRotationPoint(-7F, 13F, 59F);
      TailM1.setTextureSize(512, 512);
      TailM1.mirror = true;
      setRotation(TailM1, 0.0743572F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    EntityTriceratops Triceratops = (EntityTriceratops)entity;
    if(Triceratops.isSitting())
    {
    	if(this.isChild)
    	{
            float var8 = 2.0F;
            GL11.glPushMatrix();
            GL11.glTranslatef(0.0F, 5.0F * f5, 2.0F * f5);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
            GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
        	Body1.render(f5);
            Leg21.render(f5);
            Leg41.render(f5);
            Leg11.render(f5);
            Leg31.render(f5);
            Head1.render(f5);
            Nose1.render(f5);
            HornNose1.render(f5);
            HeadPlate1.render(f5);
            HornPlateR1.render(f5);
            HornPlateL1.render(f5);
            Rug1.render(f5);
            Tail1.render(f5);
            TailM1.render(f5);
            GL11.glPopMatrix();
    	}
    	else
    	{
    	Body1.render(f5);
        Leg21.render(f5);
        Leg41.render(f5);
        Leg11.render(f5);
        Leg31.render(f5);
        Head1.render(f5);
        Nose1.render(f5);
        HornNose1.render(f5);
        HeadPlate1.render(f5);
        HornPlateR1.render(f5);
        HornPlateL1.render(f5);
        Rug1.render(f5);
        Tail1.render(f5);
        TailM1.render(f5);
    	}
    }
    else
    {
    	if(this.isChild)
    	{
            float var8 = 2.0F;
            GL11.glPushMatrix();
            GL11.glTranslatef(0.0F, 5.0F * f5, 2.0F * f5);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
            GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
            Body.render(f5);
            Leg2.render(f5);
            Leg4.render(f5);
            Leg1.render(f5);
            Leg3.render(f5);
            Head.render(f5);
            Nose.render(f5);
            HornNose.render(f5);
            HeadPlate.render(f5);
            HornPlateR.render(f5);
            HornPlateL.render(f5);
            Rug.render(f5);
            Tail.render(f5);
            TailM.render(f5);
            GL11.glPopMatrix();
    	}
    	else
    	{
    Body.render(f5);
    Leg2.render(f5);
    Leg4.render(f5);
    Leg1.render(f5);
    Leg3.render(f5);
    Head.render(f5);
    Nose.render(f5);
    HornNose.render(f5);
    HeadPlate.render(f5);
    HornPlateR.render(f5);
    HornPlateL.render(f5);
    Rug.render(f5);
    Tail.render(f5);
    TailM.render(f5);
    	}
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    Leg3.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
